# Generated by Django 3.2.9 on 2022-04-18 19:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Crop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crop_name', models.CharField(max_length=20)),
                ('crop_desc', models.TextField()),
                ('season', models.CharField(choices=[('Rabi', 'Rabi'), ('Kharif', 'Kharif')], default='', max_length=15)),
                ('slug', models.SlugField(blank=True, max_length=255)),
                ('stock', models.IntegerField()),
                ('price', models.IntegerField()),
                ('is_available', models.BooleanField()),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('farmer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.farmerprofile')),
            ],
        ),
        migrations.CreateModel(
            name='MerchantCrop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crop', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='crop.crop')),
                ('merchant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.userprofile')),
            ],
        ),
    ]
