# Generated by Django 3.2.9 on 2022-04-18 19:34

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('crop', '0001_initial'),
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bid_start_date', models.DateField(default=datetime.date.today)),
                ('bid_close_date', models.DateField(default=datetime.date.today)),
                ('base_price', models.FloatField(default=0.0)),
                ('is_Active', models.BooleanField(default=True)),
                ('bid_for_crop', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='crop.crop')),
            ],
        ),
        migrations.CreateModel(
            name='BidEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bid_price', models.FloatField(default=0.0)),
                ('bid_time', models.DateTimeField(auto_now=True)),
                ('bid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bidding.bid')),
                ('merchant_bidding', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.userprofile')),
            ],
        ),
    ]
